# Environment settings
environment:
  size: 20
  num_drones: 4
  threshold: 0.2
  num_obstacles: 9
  render_mode: null   # Set to 'human' for visualization during traning

# Training settings
training:
  total_timesteps: 1000000
  initial_random_steps: 1000
  batch_size: 256
  learning_rate: 3e-4
  alpha: 0.2
  gamma: 0.99
  tau: 0.005
  hidden_dim: 256
  buffer_size: 1000000
  target_update_interval: 1
  save_interval: 50000
  log_interval: 1000
  eval_interval: 5000
  eval_episodes: 3

# Logging settings
logging:
  log_dir: "results/logs"
  model_dir: "models"
  video_dir: "results/videos"